name = "Tensura Pack"
author = "Vopyyy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f85d8568c220aba7678564a24de1b495d9276365b7dce27b31a35515f2cc941b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.256"
