name = "Tensura Pack"
author = "Vopyyy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6dfea32f5cbb853de8db124b2d941f578d00ccd3e7285f42ef1cf1bb659250c1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.256"
