name = "Tensura Pack"
author = "Vopyyy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e3d37243a203899756a2f13ca30814cf116f9b153237ccd7ce0d881b27197971"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.256"
